version: '3.8'

services:
  app:
    build: .
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '8082:8081'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
      # Add your ngrok token here if the tunnel fails
      # - EXPO_NGROK_AUTH_TOKEN=your_token_here
    stdin_open: true
    tty: true
    command: yarn start
